# Generated by Django 2.1.5 on 2019-12-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('songId', models.AutoField(primary_key=True, serialize=False)),
                ('Time', models.CharField(max_length=100)),
                ('Topic', models.CharField(max_length=30)),
                ('DisplayName', models.CharField(max_length=30)),
                ('Author', models.CharField(max_length=30)),
                ('Comment', models.TextField()),
            ],
        ),
    ]
