# Generated by Django 2.1.5 on 2020-01-13 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='songId',
            new_name='commentId',
        ),
    ]
