# Generated by Django 3.0.7 on 2020-06-30 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songsapp', '0002_auto_20200528_1746'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Song',
            new_name='Recommendations',
        ),
        migrations.RenameField(
            model_name='recommendations',
            old_name='song_artist',
            new_name='recommendation_song_artist',
        ),
        migrations.RenameField(
            model_name='recommendations',
            old_name='song_genre',
            new_name='recommendation_song_genre',
        ),
        migrations.RenameField(
            model_name='recommendations',
            old_name='song_name',
            new_name='recommendation_song_name',
        ),
    ]
