# Generated by Django 3.0.7 on 2020-07-01 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songsapp', '0003_auto_20200630_2125'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recommendations',
            new_name='Recommendation',
        ),
    ]
